### ISSUE TITLE
showng header file error like no such dictionary  

### ISSUE THREAD

**Issue by Vishal-Birajdar** [wolfSSL/wolfMQTT#382] opened 2023-12-13 04:43 UTC
- "wolfmqtt/mqtt_client.h" , "wolfmqtt/mqtt_packet.h" , "wolfmqtt/mqtt_sn_client.h" , "wolfmqtt/mqtt_client.h" error on these header file.
- I just download latest release file and i build it in my stm32cube ide . but header file error showing

**Comment by dgarske** [comment] 2023-12-13 16:41
@lealem47 can you review this? Seems like they need the include path for `Middlewares/Third_Party/wolfSSL_wolfMQTT_wolfMQTT` added. 
In my testing the pack did this automatically.

**Comment by lealem47** [comment] 2023-12-13 16:50
Hi @Vishal-Birajdar,
Can you confirm that you are using the wolfMQTT STM32Cube Pack? https://www.wolfssl.com/files/ide/I-CUBE-wolfMQTT.pack

More docs: https://github.com/wolfSSL/wolfMQTT/blob/master/IDE/STM32CUBE/README.md

Thanks,
Lealem @ wolfSSL

**Comment by lealem47** [comment] 2023-12-13 16:50
Note: Duplicate of ZD#17181

**Comment by Vishal-Birajdar** [comment] 2023-12-13 17:20
> @lealem47 can you review this? Seems like they need the include path for `Middlewares/Third_Party/wolfSSL_wolfMQTT_wolfMQTT` added. In my testing the pack did this automatically.

I am giving direct folder path in library path option in stm32cube ide. this is not path issue, actually " wolfmqtt/mqtt_client.h , 
  wolfmqtt/mqtt_sn_client.h "these three-header file defined or declared in some file but it not available in library.

**Comment by Vishal-Birajdar** [comment] 2023-12-13 17:38
> Hi @Vishal-Birajdar, Can you confirm that you are using the wolfMQTT STM32Cube Pack? https://www.wolfssl.com/files/ide/I-CUBE-wolfMQTT.pack
> 
> More docs: https://github.com/wolfSSL/wolfMQTT/blob/master/IDE/STM32CUBE/README.md
> 
> Thanks, Lealem @ wolfSSL

I install pack in stm32cube ide as per document but in software pack then select component there is only  wolfSSl otion available not a wolf mqtt
![Screenshot 2023-12-13 230607](https://github.com/wolfSSL/wolfMQTT/assets/151386892/874ff17d-f489-4ea8-8afc-c03e5248b53d)

**Comment by lealem47** [comment] 2023-12-13 17:40
Looks like you only have the wolfSSL software pack installed. You can install the wolfMQTT pack following the instructions here https://github.com/wolfSSL/wolfMQTT/blob/master/IDE/STM32CUBE/README.md

**Comment by Vishal-Birajdar** [comment] 2023-12-13 17:51
there is no option wolfMQTT. (In stm32cube ide ->  .ioc ->  software packs -> select components  ) Ifollow proper root but there is only wolfssl option
check below screenshoot
![2023-12-13 230607](https://github.com/wolfSSL/wolfMQTT/assets/151386892/ee6f4897-772a-4957-a530-44fdb50f1897)

**Comment by lealem47** [comment] 2023-12-13 18:11
Vishal,

I understand that it is not listed in your locally available pack list. In order to get it installed and onto that list, follow the documentation at the link I provided. https://github.com/wolfSSL/wolfMQTT/blob/master/IDE/STM32CUBE/README.md

The first few steps are:
- Download the [pack](https://www.wolfssl.com/files/ide/I-CUBE-wolfMQTT.pack).
- Run the “STM32CubeMX” tool.
- Under “Manage software installations” pane on the right, click “INSTALL/REMOVE” button.
- Select From Local and choose the downloaded pack “I-CUBE-wolfMQTT.pack”.
- Accept the GPLv2 license. Contact wolfSSL at [sales@wolfssl.com](mailto:sales@wolfssl.com) for a commercial license and support/maintenance.

**Comment by Vishal-Birajdar** [comment] 2023-12-13 18:20
Ok.
I added pack now . I will check it tomorrow because of here is mid night
now.


Thank you for support
Vishal

**Comment by Vishal-Birajdar** [comment] 2023-12-19 11:06
Hii,
 I am using ethernet connetion with LWIP in stm32 and also configure the wolfmqtt with tls enable and lwip enable in IO option.
and In example- simplemqtt.c file paste in my main src folder and change broker credential like host,port usename,password.
but it not connected to host or broker.
what is implemetation step for stm32

**Comment by lealem47** [comment] 2023-12-19 19:10
Hi @Vishal-Birajdar,

> and In example- simplemqtt.c file paste in my main src folder

I'm not sure what that means. Can me you tell about your setup? Is the broker expecting TLS? When you say it can't connect, is there an error code that you are seeing?

Can you confirm that you are calling the `mqttsimple_test()` function?

Thanks,
Lealem @ wolfSSL

**Comment by Vishal-Birajdar** [comment] 2023-12-20 04:15
I am using stm32f207 board . below are the steps 
1) enable ethernet 
2) enable LWIP with 
3) enable wolfMQTT 
   a) In IO select LWIP
   b) disable MOTT5 (False)
4) then Generate code and buid or debug  and  I check default mosquitto broker connection.
(In Middleware -> third party -> wolfmqtt -> mqttsimple -> mqttsimple.c)

**Comment by Vishal-Birajdar** [comment] 2023-12-21 05:39
problem solved now .

**Comment by Vishal-Birajdar** [comment] 2023-12-21 10:12
how can i use 'mqttclient_publish ,netconnect function in my main.c file.(showing error)
main.c generated by HAL ,
if I including wolfmqtt header file in main.c sowing error

**Comment by lealem47** [comment] 2023-12-21 16:05
I'm glad you solved the initial problem. What are the new errors that you are seeing?

To call `MqttClient_Publish()` from your main function, just add the following include to your main.c.

```
#include "wolfmqtt/mqtt_client.h"
```

Attach any relevant logs/errors if the build still fails.

**Comment by Vishal-Birajdar** [comment] 2023-12-23 05:49
[main.txt](https://github.com/wolfSSL/wolfMQTT/files/13758108/main.txt)
![Screenshot from 2023-12-23 11-17-51](https://github.com/wolfSSL/wolfMQTT/assets/151386892/5d9bc49e-b926-4af8-a570-111fc6cfbc05)
![Screenshot from 2023-12-23 11-18-05](https://github.com/wolfSSL/wolfMQTT/assets/151386892/5631fa12-bed7-4ef5-876c-03ecb54fe374)
I am copy mqttsimple.c in my main.c file but showing error .

**Comment by lealem47** [comment] 2023-12-27 00:10
It looks like you missed copying some of the includes from mqttsimple.c to main.c. Mainly these ones: 
```
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
#include <unistd.h>
```

Also, in main.c you do not have to include `userio_template.h` if you are using lwIP

**Comment by Vishal-Birajdar** [comment] 2024-01-03 08:07
I add this library and call mqttsimple_test() function in main.c .
mqttsimple.h add in core-> Inc and mqttsimple.c add in core-> Src.
if callin mqttsimple_test showing following error.

/opt/st/stm32cubeide_1.12.1/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.10.3-2021.10.linux64_1.0.200.202301161003/tools/bin/../lib/gcc/arm-none-eabi/10.3.1/../../../../arm-none-eabi/bin/ld: ./Core/Src/main.o: in function `main':
/home/pvipl/STM32CubeIDE/workspace_1.12.1/wolfmqtt/Debug/../Core/Src/main.c:81: undefined reference to `mqttsimple_test'
collect2: error: ld returned 1 exit status
make: *** [makefile:83: wolfmqtt.elf] Error 1
"make -j4 all" terminated with exit code 2. Build might be incomplete.

13:24:08 Build Failed. 3 errors, 1 warnings. (took 11s.713ms)

![Screenshot from 2024-01-03 13-24-34](https://github.com/wolfSSL/wolfMQTT/assets/151386892/54176fbc-4d55-4bc5-87fc-956f33fb0e0b)
![Screenshot from 2024-01-03 13-25-56](https://github.com/wolfSSL/wolfMQTT/assets/151386892/373bdaf7-a554-4fd4-a527-8d4cec403e7f)
![Screenshot from 2024-01-03 13-26-14](https://github.com/wolfSSL/wolfMQTT/assets/151386892/3f4b0793-483b-4560-8716-1117f97b8e51)

**Comment by lealem47** [comment] 2024-01-03 17:27
It looks like that the mqttsimple example is guarded by the `HAVE_SOCKET` macro. Try adding `#define HAVE_SOCKET` to the `wolfSSL.I-CUBE-wolfMQTT_conf.h` file and recompiling

**Comment by Vishal-Birajdar** [comment] 2024-01-03 18:12
after adding #define HAVE_SOCKET showing error in mqttsimple.c -> #include <netinet/in.h> no such file error
compilation terminated.
make: *** [Core/Src/subdir.mk:37: Core/Src/mqttsimple.o] Error 1
make: *** Waiting for unfinished jobs....
../Core/mqttsimple/mqttsimple.c:38:10: fatal error: netinet/in.h: No such file or directory
   38 | #include <netinet/in.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [Core/mqttsimple/subdir.mk:19: Core/mqttsimple/mqttsimple.o] Error 1
"make -j4 all" terminated with exit code 2. Build might be incomplete.

23:42:11 Build Failed. 5 errors, 0 warnings. (took 1s.693ms)

**Comment by lealem47** [comment] 2024-01-03 18:22
That header should not be included if using lwip (The desired functionality is already provided in `lwip/netdb.h`). I will make that modification to the example but for your case you can just comment it out.

**Comment by Vishal-Birajdar** [comment] 2024-01-03 18:50
showing error when i comment out it.
![Screenshot from 2024-01-04 00-18-15](https://github.com/wolfSSL/wolfMQTT/assets/151386892/87daa48a-4c52-465c-a47f-221d6e3556ff)

**Comment by Vishal-Birajdar** [comment] 2024-01-03 19:08
this is my mqtt configuration
![Screenshot from 2024-01-04 00-36-49](https://github.com/wolfSSL/wolfMQTT/assets/151386892/ca006e82-f8ea-4089-85f1-91fcf1ac8c70)
![Screenshot from 2024-01-04 00-37-13](https://github.com/wolfSSL/wolfMQTT/assets/151386892/a17791f5-49ff-4b5f-9b72-f495dc631b5d)

**Comment by lealem47** [comment] 2024-01-03 19:29
I'm able to successfully able to compile your exact scenario after commenting out that header. Can you share your generated `wolfSSL.I-CUBE-wolfMQTT_conf.h` file?

**Comment by Vishal-Birajdar** [comment] 2024-01-04 04:11
/home/pvipl/STM32CubeIDE/MQTT_E/wolfMQTT/wolfSSL.I-CUBE-wolfMQTT_conf.h

[wolfSSL.I-CUBE-wolfMQTT_conf.txt](https://github.com/wolfSSL/wolfMQTT/files/13826046/wolfSSL.I-CUBE-wolfMQTT_conf.txt)

**Comment by lealem47** [comment] 2024-01-15 19:09
Could you try adding ` #include "examples/mqttport.h" ` to the top of the `mqttsimple.c` file?

**Comment by lealem47** [comment] 2024-01-15 19:13
Could you also try  manually adding WOLFSSL_LWIP to the `wolfSSL.I-CUBE-wolfMQTT_conf.h` file?

**Comment by Vishal-Birajdar** [comment] 2024-01-18 17:43
showing error .
Can I copy mqttsimple.c function in main.c. as it  to implement mqtt .
like read,write,connect function as it is in my main.c file.

**Comment by lealem47** [comment] 2024-01-18 19:00
We are not making progress this way. I see that you have opened a support ticket regarding this issue. I will reach out to you there and we can schedule a call to debug and get this working for you.

**Comment by Vishal-Birajdar** [comment] 2024-01-19 10:28
I will be waiting for your call.
+918007904460

**Comment by lealem47** [comment] 2024-01-22 17:19
Resolved offline. The issue was fixed by enabling `LWIP_DNS (DNS Module)` in the LWIP general settings.

**Closed by lealem47** 2024-01-22 17:19 UTC
